### ISSUE TITLE
pps2.jks

### ISSUE THREAD

**Issue by planonsoftware** [planonsoftware/OPENSHIFT_Pn_Installer#40]
INFO [18-12-2014 11:24:44] Reading PSS properties from: /var/lib/openshift/5492b90c83e702b5c800008d/planon/PlanonProCenter/tomcat-7.0.54/conf/ticket.properties
 INFO [18-12-2014 11:24:44] Reading JNDI properties from: /var/lib/openshift/5492b90c83e702b5c800008d/planon/PlanonProCenter/tomcat-7.0.54/conf/jndi.properties
 INFO [18-12-2014 11:24:44] Loaded properties
nl.planon.hades.exception.PnRuntimeException: Exception during signer creation!
        at nl.planon.hades.client.authentication.jboss.PnJBossSessionSigner.loadPrivateKey(PnJBossSessionSigner.java:186)
        at nl.planon.hades.client.authentication.jboss.PnJBossSessionSigner.loadPrivateKey(PnJBossSessionSigner.java:145)
        at nl.planon.telesto.mobility.server.authentication.framework.AuthenticatorApplication.init(AuthenticatorApplication.java:143)
        at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:726)
        at org.apache.felix.http.base.internal.handler.FilterHandler.init(FilterHandler.java:53)
        at org.apache.felix.http.base.internal.handler.HandlerRegistry.addFilter(HandlerRegistry.java:78)
        at org.apache.felix.http.base.internal.service.HttpServiceImpl.registerFilter(HttpServiceImpl.java:70)
        at nl.planon.telesto.mobility.server.authentication.osgi.Activator.deploy(Activator.java:147)
        at nl.planon.telesto.mobility.server.authentication.osgi.Activator.addHttpService(Activator.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by maquae** [comment]
ticket not supported
